name:                cmake-file-api
version:             0.1.0.0
github:              "umogSlayer/cmake-file-api"
license:             BSD3
author:              "Vladimir Bayrashevskiy"
maintainer:          "vovanhood@gmail.com"
copyright:           "2019 Vladimir Bayrashevskiy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/umogSlayer/cmake-file-api#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- containers
- bytestring
- utf8-string
- directory

library:
  source-dirs: src

executables:
  cmake-file-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cmake-file-api

tests:
  cmake-file-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cmake-file-api
